### ISSUE TITLE
Todo 도메인(요구사항) 분석 내용 

### ISSUE THREAD

**Issue by tuioe5679** [GameCenters/Todo#3]
### Todo 도메인 분석 
**Todo**는 할일을 관리하는 제품으로 **CRUD**가 필요할것 같다고 생각합니다 

- **Create**: 할일을 추가하는 작업으로 저장할 공간을 마련하고 내용에 대해 저장한다                    
                    저장할 데이터는 할일,생성일자로 생각하고 있습니다 

- **Read**: 추가가된 일을 알기 쉽게 보기위해서 저장된 데이터를 불러와 웹에 출력 

- **Update**: 추가된 할일이 변경될수 있기때문에 선택한 일을 수정할수 있는 기능이 필요할것 같습니다 
                      생성일자도 수정한 날짜로 변경되도록 하면 좋을것 같아요

- **Delete**: 할일이 끝났을때는 삭제하는 작업을 통해서 저장된 데이터를 제거 
                     삭제된 일은 웹에서도 삭제되어야 한다

**Comment by tuioe5679** [comment]
@rhea-so 코멘트 남기기 (이게 맞는거죠)

**Comment by rhea-so** [comment]
잘하셨습니당 !! 

각 요청들을 Interface로 한번 정의해보시겠어용?

**Comment by tuioe5679** [comment]
네 회의전까지 해보겠습니다
